    image: node:latest
    
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl

    stages:
      - build
      - test
      - production

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    testing_testing:
      stage: test
      script: npm test